name: Build Flutter APK

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout project
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # ضع هنا نسخة Flutter الخاصة بك

      # Get packages
      - name: Get dependencies
        run: flutter pub get

      # Build APK (release)
      - name: Build APK
        run: flutter build apk --release

      # رفع APK إلى Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
